export const financiamentos = [
    {
      valorImovel: 350000,
      valorFinanciamento: 300000,
      valorEntrada: 50000,
      nomeCliente: "Carlos Silva",
      emailCliente: "carlos.silva@email.com",
      telefoneCliente: "(11) 98765-4321",
      nomeConsultor: "Mariana Almeida",
      emailConsultor: "mariana.almeida@fintech.com",
      telefoneConsultor: "(11) 91234-5678",
      statusProcesso: "Em andamento",
      numeroProtocolo: "A1B2C3D4",
      numeroParcelas: 360,
    },
    {
      valorImovel: 450000,
      valorFinanciamento: 400000,
      valorEntrada: 50000,
      nomeCliente: "Joana Pereira",
      emailCliente: "joana.pereira@email.com",
      telefoneCliente: "(21) 97865-1234",
      nomeConsultor: "Ricardo Santos",
      emailConsultor: "ricardo.santos@fintech.com",
      telefoneConsultor: "(21) 92345-6789",
      statusProcesso: "Vistoria",
      numeroProtocolo: "E5F6G7H8",
      numeroParcelas: 420,
    },
    {
      valorImovel: 280000,
      valorFinanciamento: 250000,
      valorEntrada: 30000,
      nomeCliente: "Fernanda Costa",
      emailCliente: "fernanda.costa@email.com",
      telefoneCliente: "(31) 98654-3210",
      nomeConsultor: "Paulo Gomes",
      emailConsultor: "paulo.gomes@fintech.com",
      telefoneConsultor: "(31) 92345-8765",
      statusProcesso: "Assinatura de documento",
      numeroProtocolo: "I9J0K1L2",
      numeroParcelas: 240,
    },
    {
      valorImovel: 700000,
      valorFinanciamento: 600000,
      valorEntrada: 100000,
      nomeCliente: "Gabriel Lima",
      emailCliente: "gabriel.lima@email.com",
      telefoneCliente: "(41) 98123-4567",
      nomeConsultor: "Ana Beatriz",
      emailConsultor: "ana.beatriz@fintech.com",
      telefoneConsultor: "(41) 98765-4321",
      statusProcesso: "Em andamento",
      numeroProtocolo: "M3N4O5P6",
      numeroParcelas: 420,
    },
    {
      valorImovel: 500000,
      valorFinanciamento: 450000,
      valorEntrada: 50000,
      nomeCliente: "Rafael Souza",
      emailCliente: "rafael.souza@email.com",
      telefoneCliente: "(51) 98234-5678",
      nomeConsultor: "Juliana Farias",
      emailConsultor: "juliana.farias@fintech.com",
      telefoneConsultor: "(51) 99123-4567",
      statusProcesso: "Vistoria",
      numeroProtocolo: "Q7R8S9T0",
      numeroParcelas: 300,
    },
    {
      valorImovel: 650000,
      valorFinanciamento: 580000,
      valorEntrada: 70000,
      nomeCliente: "Aline Duarte",
      emailCliente: "aline.duarte@email.com",
      telefoneCliente: "(61) 98345-6789",
      nomeConsultor: "Roberto Lima",
      emailConsultor: "roberto.lima@fintech.com",
      telefoneConsultor: "(61) 99456-7890",
      statusProcesso: "Assinatura de documento",
      numeroProtocolo: "U1V2W3X4",
      numeroParcelas: 360,
    },
    {
      valorImovel: 320000,
      valorFinanciamento: 290000,
      valorEntrada: 30000,
      nomeCliente: "Lucas Andrade",
      emailCliente: "lucas.andrade@email.com",
      telefoneCliente: "(71) 98876-5432",
      nomeConsultor: "Carla Mendes",
      emailConsultor: "carla.mendes@fintech.com",
      telefoneConsultor: "(71) 97543-2109",
      statusProcesso: "Em andamento",
      numeroProtocolo: "Y5Z6A7B8",
      numeroParcelas: 240,
    },
    {
      valorImovel: 400000,
      valorFinanciamento: 350000,
      valorEntrada: 50000,
      nomeCliente: "Beatriz Silva",
      emailCliente: "beatriz.silva@email.com",
      telefoneCliente: "(81) 98234-5678",
      nomeConsultor: "Pedro Henrique",
      emailConsultor: "pedro.henrique@fintech.com",
      telefoneConsultor: "(81) 98765-4321",
      statusProcesso: "Vistoria",
      numeroProtocolo: "C9D0E1F2",
      numeroParcelas: 360,
    },
    {
      valorImovel: 750000,
      valorFinanciamento: 700000,
      valorEntrada: 50000,
      nomeCliente: "Camila Rocha",
      emailCliente: "camila.rocha@email.com",
      telefoneCliente: "(91) 98123-4567",
      nomeConsultor: "Thiago Nunes",
      emailConsultor: "thiago.nunes@fintech.com",
      telefoneConsultor: "(91) 91234-5678",
      statusProcesso: "Assinatura de documento",
      numeroProtocolo: "G3H4I5J6",
      numeroParcelas: 420,
    },
    {
      valorImovel: 480000,
      valorFinanciamento: 430000,
      valorEntrada: 50000,
      nomeCliente: "Sofia Martins",
      emailCliente: "sofia.martins@email.com",
      telefoneCliente: "(31) 98456-7890",
      nomeConsultor: "André Borges",
      emailConsultor: "andre.borges@fintech.com",
      telefoneConsultor: "(31) 99321-4567",
      statusProcesso: "Em andamento",
      numeroProtocolo: "K7L8M9N0",
      numeroParcelas: 300,
    },
  ];
  
  console.log(financiamentos);
  